#!/usr/bin/env rake
require 'fileutils'

namespace :assets do
  task :precompile do
    rails_root = File.expand_path('..', __FILE__)
    asset_root = File.join(rails_root, 'public', 'assets')
    FileUtils.mkdir_p(File.join(asset_root))
    File.open(File.join(asset_root, 'manifest.yml'), 'w+') do |file|
      file.write('list of compiled assets...')
    end
  end
end

